[project]
name = 'DecentralizedHR'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.DecentralizedHR]
path = 'contracts/DecentralizedHR.clar'
clarity_version = 3
epoch = 3.1

[contracts.compensation-benchmarking]
path = 'contracts/compensation-benchmarking.clar'
clarity_version = 3
epoch = 3.1

[contracts.skills-verification]
path = 'contracts/skills-verification.clar'
clarity_version = 3
epoch = 3.1

[contracts.time-off-management]
path = 'contracts/time-off-management.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
